from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SUBJECT = ROOT / "revision/alpha4/REVISION.aset"
FORTH = ROOT / "revision/alpha4/operational/components.forth"
REL = ROOT / "revision/alpha4/formal/RevisionRelations.tla"
SEED_PROJECTION = ROOT / "revision/alpha4/formal/SeedProjection.tla"
CAUSAL = ROOT / "revision/alpha4/causal/components.petri"


def sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def source_digest(paths: tuple[Path, ...]) -> str:
    digest = hashlib.sha256()
    for path in sorted(paths, key=lambda item: item.relative_to(ROOT).as_posix()):
        relative = path.relative_to(ROOT).as_posix()
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return "sha256:" + digest.hexdigest()


def _subject_pair() -> tuple[str, str, str, str]:
    for raw in SUBJECT.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line.startswith("PAIR "):
            tokens = line.split()
            if len(tokens) != 5:
                raise RuntimeError("invalid Revision PAIR declaration")
            return (tokens[1], tokens[2], tokens[3], tokens[4])
    raise RuntimeError("Revision PAIR declaration missing")


def companion_record() -> dict[str, object]:
    component_id, operational_word, formal_operator, proof = _subject_pair()
    forth = FORTH.read_text(encoding="utf-8")
    relational = REL.read_text(encoding="utf-8")
    projection = SEED_PROJECTION.read_text(encoding="utf-8")
    required_forth = (
        "VALID-PROPOSAL?",
        "FRESH-PROPOSAL?",
        "APPEND-PROPOSAL",
    )
    if not all(token in forth for token in required_forth):
        raise RuntimeError("Revision operational expression drift")
    required_relational = (
        "p.target = p.transition.genesis",
        "tr.fromState # tr.toState",
        "p \\notin s",
        "t = s \\cup {p}",
    )
    if not all(token in relational for token in required_relational):
        raise RuntimeError("Revision relational expression drift")
    if "Seed!ObserveUnknown" not in projection:
        raise RuntimeError("Revision Seed projection drift")
    return {
        "component_id": component_id,
        "operational_word": operational_word,
        "formal_operator": formal_operator,
        "pairing_proof": proof,
        "state": "proposals",
        "transition": "PROPOSE-REVISION",
        "validity": "target=genesis AND from-state!=to-state",
        "freshness": "proposal NOT-IN proposals",
        "effect": "append proposal",
        "seed_projection": "OBSERVE-UNKNOWN",
        "terminal_recognition_owned": False,
        "effect_permission_owned": False,
    }


def write_english(target: Path, record: dict[str, object]) -> None:
    lines = [
        "# ASET Revision 0.4alpha — generated Revision release companion",
        "",
        "Generated by release tooling. Membership: external companion. Semantic precedence: none.",
        "",
        "### ASET-REVISION-COMPONENT-PROPOSE-REVISION",
        f"Operational: `{record['operational_word']}`",
        f"Relational: `{record['formal_operator']}`",
        f"State: `{record['state']}`",
        f"Transition: `{record['transition']}`",
        f"Validity: `{record['validity']}`",
        f"Freshness: `{record['freshness']}`",
        f"Effect: `{record['effect']}`",
        f"SeedProjection: `{record['seed_projection']}`",
        "TerminalRecognitionOwned: `FALSE`",
        "EffectPermissionOwned: `FALSE`",
        "",
        "A successful proposal appends one exact revision transition. Invalid or replayed proposals are rejected without changing the proposal set.",
        "The companion does not recognize a revision and does not grant effect permission; target-local Seed recognition remains external.",
        "",
    ]
    target.write_text("\n".join(lines), encoding="utf-8")


def write_python(target: Path, record: dict[str, object], identity_digest: str) -> None:
    text = f'''"""Generated ASET Revision 0.4alpha Revision Python companion.

External release companion. Semantic precedence: none.
"""

from __future__ import annotations

from typing import Iterable

SUBJECT_ID = "ASET-REVISION-0.4-ALPHA"
VERSION = "0.4alpha"
SEMANTIC_PRECEDENCE = "NONE"
SOURCE_BYTE_IDENTITY_DIGEST = {identity_digest!r}
COMPONENT_ID = {str(record["component_id"])!r}
OPERATIONAL_WORD = {str(record["operational_word"])!r}
FORMAL_OPERATOR = {str(record["formal_operator"])!r}
SEED_PROJECTION = "OBSERVE-UNKNOWN"
TERMINAL_RECOGNITION_OWNED = False
EFFECT_PERMISSION_OWNED = False

Proposal = tuple[str, str, str, str]
State = tuple[Proposal, ...]


def proposal(
    target: str,
    genesis: str,
    from_state: str,
    to_state: str,
) -> Proposal:
    return (target, genesis, from_state, to_state)


def state(proposals: Iterable[Proposal] = ()) -> State:
    return tuple(sorted(set(proposals)))


def valid_proposal(candidate: Proposal) -> bool:
    if not isinstance(candidate, tuple) or len(candidate) != 4:
        return False
    target, genesis, from_state, to_state = candidate
    return (
        all(isinstance(item, str) for item in candidate)
        and target == genesis
        and from_state != to_state
    )


def propose_revision(current: State, candidate: Proposal) -> State:
    normalized = state(current)
    if any(not valid_proposal(item) for item in normalized):
        raise ValueError("invalid proposal state")
    if not valid_proposal(candidate):
        raise ValueError("invalid revision proposal")
    if candidate in normalized:
        raise ValueError("revision proposal is not fresh")
    return state((*normalized, candidate))
'''
    target.write_text(text, encoding="utf-8")


def write_python_sqlite(target: Path, base_expression_sha256: str) -> None:
    text = f'''"""Generated ASET Revision 0.4alpha Revision Python SQLite persistence extension.

Persistence extension of the exact generated Python companion.
Semantic delta: none. Semantic precedence: none.
"""

from __future__ import annotations

import hashlib
import importlib.util
import sqlite3
from pathlib import Path
from typing import Any

BASE_EXPRESSION_SHA256 = {base_expression_sha256!r}
BASE_EXPRESSION_PATH = (
    Path(__file__).resolve().parents[1] / "python" / "aset_revision_alpha4.py"
)
SEMANTIC_DELTA = "NONE"
SEMANTIC_PRECEDENCE = "NONE"


def _sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _load_base_expression() -> Any:
    if _sha256(BASE_EXPRESSION_PATH) != BASE_EXPRESSION_SHA256:
        raise RuntimeError("base Python expression byte identity mismatch")
    spec = importlib.util.spec_from_file_location(
        "aset_revision_alpha4_base_expression",
        BASE_EXPRESSION_PATH,
    )
    if spec is None or spec.loader is None:
        raise RuntimeError("base Python expression cannot be loaded")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_base_expression = _load_base_expression()


class SQLiteStore:
    def __init__(self, path: str | Path) -> None:
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with self._connect() as connection:
            connection.execute(
                "CREATE TABLE IF NOT EXISTS proposals ("
                "target TEXT NOT NULL, "
                "genesis TEXT NOT NULL, "
                "from_state TEXT NOT NULL, "
                "to_state TEXT NOT NULL, "
                "PRIMARY KEY (target, genesis, from_state, to_state), "
                "CHECK (target = genesis), "
                "CHECK (from_state <> to_state)"
                ")"
            )

    def _connect(self) -> sqlite3.Connection:
        return sqlite3.connect(self.path)

    def load(self) -> tuple[tuple[str, str, str, str], ...]:
        with self._connect() as connection:
            rows = connection.execute(
                "SELECT target, genesis, from_state, to_state "
                "FROM proposals ORDER BY target, genesis, from_state, to_state"
            ).fetchall()
        return tuple(tuple(str(value) for value in row) for row in rows)

    def replace(self, current: tuple[tuple[str, str, str, str], ...]) -> None:
        normalized = _base_expression.state(current)
        if any(not _base_expression.valid_proposal(item) for item in normalized):
            raise ValueError("invalid persistent proposal state")
        with self._connect() as connection:
            connection.execute("BEGIN IMMEDIATE")
            connection.execute("DELETE FROM proposals")
            connection.executemany(
                "INSERT INTO proposals (target, genesis, from_state, to_state) "
                "VALUES (?, ?, ?, ?)",
                normalized,
            )

    def propose_revision(
        self,
        candidate: tuple[str, str, str, str],
    ) -> tuple[tuple[str, str, str, str], ...]:
        with self._connect() as connection:
            connection.execute("BEGIN IMMEDIATE")
            rows = connection.execute(
                "SELECT target, genesis, from_state, to_state "
                "FROM proposals ORDER BY target, genesis, from_state, to_state"
            ).fetchall()
            current = tuple(tuple(str(value) for value in row) for row in rows)
            result = _base_expression.propose_revision(current, candidate)
            connection.execute(
                "INSERT INTO proposals (target, genesis, from_state, to_state) "
                "VALUES (?, ?, ?, ?)",
                candidate,
            )
            return result
'''
    target.write_text(text, encoding="utf-8")


def write_python_sqlite_binding(
    target: Path,
    base_expression: Path,
    extension: Path,
) -> None:
    value = {
        "document_type": "aset-revision-python-persistence-extension-binding",
        "project": "ASET Revision",
        "extension_id": "ASET-REVISION-PYTHON-SQLITE-PERSISTENCE-V1",
        "relation": "PERSISTENCE_EXTENSION",
        "semantic_delta": "NONE",
        "semantic_precedence": "NONE",
        "base_expression": {
            "profile": "python",
            "path": "python/aset_revision_alpha4.py",
            "sha256": sha256(base_expression),
        },
        "extension": {
            "profile": "python-sqlite",
            "path": "python-sqlite/aset_revision_alpha4_sqlite.py",
            "sha256": sha256(extension),
            "storage_backend": "python-stdlib-sqlite3",
        },
        "assurance_scope": [
            "EXACT_BASE_EXPRESSION_BYTE_BINDING",
            "BASE_EXPRESSION_OBSERVATIONAL_CONGRUENCE",
            "ATOMIC_SUCCESSFUL_COMMIT",
            "ROLLBACK_ON_BASE_EXPRESSION_REJECTION",
            "RESTART_ROUND_TRIP",
            "NO_RECOGNITION_STATE_STORAGE",
        ],
        "not_claimed": [
            "UNIVERSAL_CONCURRENCY_CORRECTNESS",
            "STORAGE_CORRUPTION_RECOVERY",
        ],
    }
    target.write_text(
        json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def build_release_profiles(root: Path, output: Path) -> dict[str, object]:
    if root.resolve() != ROOT.resolve():
        raise RuntimeError("release profile generator must run against repository root")
    if output.exists():
        shutil.rmtree(output)
    (output / "en").mkdir(parents=True)
    (output / "python").mkdir(parents=True)
    (output / "python-sqlite").mkdir(parents=True)

    record = companion_record()
    identity = source_digest((SUBJECT, FORTH, REL, CAUSAL, SEED_PROJECTION))
    english = output / "en/Revision.md"
    python_expression = output / "python/aset_revision_alpha4.py"
    sqlite_extension = output / "python-sqlite/aset_revision_alpha4_sqlite.py"
    sqlite_binding = output / "python-sqlite/PERSISTENCE_EXTENSION.json"
    write_english(english, record)
    write_python(python_expression, record, identity)
    write_python_sqlite(sqlite_extension, sha256(python_expression))
    write_python_sqlite_binding(sqlite_binding, python_expression, sqlite_extension)

    return {
        "record": record,
        "source_byte_identity_digest": identity,
        "english": english,
        "python": python_expression,
        "python_sqlite": sqlite_extension,
        "python_sqlite_binding": sqlite_binding,
    }
